# Decap CMS 配置
# repo 填你的 GitHub 仓库，例如: yourname/yourname.github.io

backend:
  name: github
  repo: MieoM79/MieoM79.github.io
  branch: main
  client_id: Ov23ctdKhR4EYtbiPS9s

publish_mode: editorial_workflow

media_folder: source/images
public_folder: /images

collections:
  - name: posts
    label: 文章
    folder: source/_posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 日期, name: date, widget: datetime }
      - { label: 标签, name: tags, widget: list, default: ['随笔'] }
      - { label: 正文, name: body, widget: markdown }